---

- name: save root token variable
  set_fact:
    root_token: "s.HaIMw1DzIieknCprrQcqHCam"

- name: Vault heath check
  uri:
    url: "http://127.0.0.1:{{ vault_port }}/v1/sys/health"
    validate_certs: no
    method: GET
    status_code: 200
  retries: 10
  delay: 5

- name: get status of transform secrets engine
  uri:
    url: "http://127.0.0.1:{{ vault_port }}/v1/sys/mounts"
    method: GET
    headers:
      X-Vault-Token: "{{ root_token }}"
  failed_when:
    - no
  register: vault_status_transform

- name: enable transform secrets engine
  uri:
    url: "http://127.0.0.1:{{ vault_port }}/v1/sys/mounts/transform"
    method: POST
    headers:
      X-Vault-Token: "{{ root_token }}"
    body:
      type: "{{ transform_path }}"
    body_format: json
    status_code:
      - 200
      - 204
  when:
    - "'transform/' not in vault_status_transform.json.data"

- name: create transform secrets engine role
  uri:
    url: "http://127.0.0.1:{{ vault_port }}/v1/transform/role/encryption"
    method: POST
    headers:
      X-Vault-Token: "{{ root_token }}"
    body: "{{ lookup('template','transform_roles.json.j2') }}"
    body_format: json
    status_code:
      - 200
      - 204

- name: create transformation creditcardnumber
  uri:
    url: "http://127.0.0.1:{{ vault_port }}/v1/transform/transformations/fpe/creditcardnumber"
    method: POST
    headers:
      X-Vault-Token: "{{ root_token }}"
    body: "{{ lookup('file','transformation_creditcard.json') }}"
    body_format: json
    status_code:
      - 200
      - 204

- name: create transformation socialsecuritynumber
  uri:
    url: "http://127.0.0.1:{{ vault_port }}/v1/transform/transformations/fpe/socialsecuritynumber"
    method: POST
    headers:
      X-Vault-Token: "{{ root_token }}"
    body: "{{ lookup('file','transformation_socialsecurity.json') }}"
    body_format: json
    status_code:
      - 200
      - 204

- name: create transformation driverslicense
  uri:
    url: "http://127.0.0.1:{{ vault_port }}/v1/transform/transformations/fpe/driverslicense"
    method: POST
    headers:
      X-Vault-Token: "{{ root_token }}"
    body: "{{ lookup('file','transformation_driverslicense.json') }}"
    body_format: json
    status_code:
      - 200
      - 204


- name: create driverslicense template
  ansible.builtin.uri:
    url: "http://127.0.0.1:{{ vault_port }}/transform/template/driverslicense-template"
    method: POST
    headers:
      X-Vault-Token: "{{ root_token }}"
    body:
      type: regex
      pattern: "(\\d{10})"
      alphabet: builtin/alphanumericupper
    body_format: json
    status_code:
      - 200
      - 204